FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src ./src
COPY bot ./bot
COPY config ./config
COPY alembic.ini .
COPY alembic ./alembic

CMD ["python", "-m", "bot.main"]
